class Match(object):
    RATIO = 90
    LIMIT = 10
    CITY_EQUIVALENT = set(['place', 'district'])
    TOWN_EQUIVALENT = set(['place'])
    COUNTY_EQUIVALENT = set(['county', 'parish', 'census_area',
                             'borough', 'region'])
    COURT_EQUIVALENT = set(['chancery_court', 'superior_court',
                            'supreme_court', 'court_of_appeals',
                            'district_court', 'circuit_court',
                            'constable_districts']),
    COUNCIL_EQUIVALENT = set(['council_district', 'commissioner_district'])
    WARD_EQUILVALET = set(['anc', 'ward', 'precinct'])
    STATE_EQUIVALENT = set(['state', 'territory', 'district'])
    CONVERSIONS = {
        'city': CITY_EQUIVALENT,
        'town': TOWN_EQUIVALENT,
        'township': TOWN_EQUIVALENT,
        'village': TOWN_EQUIVALENT,
        'county': COUNTY_EQUIVALENT,
        'parish': COUNTY_EQUIVALENT,
        'census_area': COUNTY_EQUIVALENT,
        'borough': COUNTY_EQUIVALENT,
        'region': COUNTY_EQUIVALENT,
        'state': STATE_EQUIVALENT,
        'territory': STATE_EQUIVALENT,
        'council': COUNCIL_EQUIVALENT,
        'commissioner': COUNCIL_EQUIVALENT,
        'court': COURT_EQUIVALENT,
        'ward': WARD_EQUILVALET,
        'anc': WARD_EQUILVALET,
        'precinct': WARD_EQUILVALET,
        'school': set(['school_board']),
        'country': set(['country']),
        'cd': set(['cd']),
        'sldl': set(['sldl']),
        'sldu': set(['sldu'])}


class Ocdid(object):
    NONCURRENT_DIST = set([
        'ocd-division/country:us/state:ny/county:oneida/council_district:24',
        'ocd-division/country:us/state:ny/county:oneida/council_district:25',
        'ocd-division/country:us/state:ny/county:oneida/council_district:26',
        'ocd-division/country:us/state:ny/county:oneida/council_district:27',
        'ocd-division/country:us/state:ny/county:oneida/council_district:28',
        'ocd-division/country:us/state:ny/county:oneida/council_district:29',
        'ocd-division/country:us/state:ca/sldu:assigned-10',
        'ocd-division/country:us/state:ca/sldu:assigned-14',
        'ocd-division/country:us/state:ca/sldu:assigned-17',
        'ocd-division/country:us/state:ca/sldu:assigned-18',
        'ocd-division/country:us/state:ca/sldu:assigned-2',
        'ocd-division/country:us/state:ca/sldu:assigned-20',
        'ocd-division/country:us/state:ca/sldu:assigned-22',
        'ocd-division/country:us/state:ca/sldu:assigned-23',
        'ocd-division/country:us/state:ca/sldu:assigned-24',
        'ocd-division/country:us/state:ca/sldu:assigned-25',
        'ocd-division/country:us/state:ca/sldu:assigned-28',
        'ocd-division/country:us/state:ca/sldu:assigned-29',
        'ocd-division/country:us/state:ca/sldu:assigned-30',
        'ocd-division/country:us/state:ca/sldu:assigned-31',
        'ocd-division/country:us/state:ca/sldu:assigned-32',
        'ocd-division/country:us/state:ca/sldu:assigned-34',
        'ocd-division/country:us/state:ca/sldu:assigned-35',
        'ocd-division/country:us/state:ca/sldu:assigned-36',
        'ocd-division/country:us/state:ca/sldu:assigned-37',
        'ocd-division/country:us/state:ca/sldu:assigned-38',
        'ocd-division/country:us/state:ca/sldu:assigned-4',
        'ocd-division/country:us/state:ca/sldu:assigned-40',
        'ocd-division/country:us/state:ca/sldu:assigned-6',
        'ocd-division/country:us/state:ia/cd:5',
        'ocd-division/country:us/state:mi/cd:15',
        'ocd-division/country:us/state:ny/cd:28',
        'ocd-division/country:us/state:ny/cd:29',
        'ocd-division/country:us/state:oh/cd:17',
        'ocd-division/country:us/state:oh/cd:18',
        'ocd-division/country:us/state:pa/cd:19',
        'ocd-division/country:us/state:nj/cd:13',
        'ocd-division/country:us/state:il/cd:19',
        'ocd-division/country:us/state:ma/cd:10',
        'ocd-division/country:us/state:la/cd:7',
        'ocd-division/country:us/state:mo/cd:9',
        'ocd-division/country:us/state:vt/sldl:addison-rutland-1',
        'ocd-division/country:us/state:vt/sldl:bennington-rutland-1',
        'ocd-division/country:us/state:vt/sldl:caledonia-washington-1',
        'ocd-division/country:us/state:vt/sldl:chittenden-1-1',
        'ocd-division/country:us/state:vt/sldl:chittenden-1-2',
        'ocd-division/country:us/state:vt/sldl:chittenden-3-1',
        'ocd-division/country:us/state:vt/sldl:chittenden-3-2',
        'ocd-division/country:us/state:vt/sldl:chittenden-3-3',
        'ocd-division/country:us/state:vt/sldl:chittenden-3-4',
        'ocd-division/country:us/state:vt/sldl:chittenden-3-5',
        'ocd-division/country:us/state:vt/sldl:chittenden-3-6',
        'ocd-division/country:us/state:vt/sldl:chittenden-3-7',
        'ocd-division/country:us/state:vt/sldl:chittenden-3-8',
        'ocd-division/country:us/state:vt/sldl:chittenden-3-9',
        'ocd-division/country:us/state:vt/sldl:chittenden-3-10',
        'ocd-division/country:us/state:vt/sldl:chittenden-4',
        'ocd-division/country:us/state:vt/sldl:chittenden-8',
        'ocd-division/country:us/state:vt/sldl:chittenden-9',
        'ocd-division/country:us/state:vt/sldl:essex-caledonia-1',
        'ocd-division/country:us/state:vt/sldl:essex-caledonia-2',
        'ocd-division/country:us/state:vt/sldl:franklin-3',
        'ocd-division/country:us/state:vt/sldl:grand_isle-chittenden-1',
        'ocd-division/country:us/state:vt/sldl:lamoille-4',
        'ocd-division/country:us/state:vt/sldl:orange-addison-1',
        'ocd-division/country:us/state:vt/sldl:orange-caledonia-1',
        'ocd-division/country:us/state:vt/sldl:orleans-caledonia-1',
        'ocd-division/country:us/state:vt/sldl:orleans-franklin-1',
        'ocd-division/country:us/state:vt/sldl:rutland-1-1',
        'ocd-division/country:us/state:vt/sldl:rutland-1-2',
        'ocd-division/country:us/state:vt/sldl:rutland-7',
        'ocd-division/country:us/state:vt/sldl:rutland-8',
        'ocd-division/country:us/state:vt/sldl:washington-3-1',
        'ocd-division/country:us/state:vt/sldl:washington-3-2',
        'ocd-division/country:us/state:vt/sldl:washington-3-3',
        'ocd-division/country:us/state:vt/sldl:washington-chittenden-1',
        'ocd-division/country:us/state:vt/sldl:windham-2',
        'ocd-division/country:us/state:vt/sldl:windham-3-1',
        'ocd-division/country:us/state:vt/sldl:windham-3-2',
        'ocd-division/country:us/state:vt/sldl:windham-3-3',
        'ocd-division/country:us/state:vt/sldl:windham-bennington-1',
        'ocd-division/country:us/state:vt/sldl:windsor-1-1',
        'ocd-division/country:us/state:vt/sldl:windsor-1-2',
        'ocd-division/country:us/state:vt/sldl:windsor-3',
        'ocd-division/country:us/state:vt/sldl:windsor-4',
        'ocd-division/country:us/state:vt/sldl:windsor-6-1',
        'ocd-division/country:us/state:vt/sldl:windsor-6-2',
        'ocd-division/country:us/state:vt/sldl:windsor-rutland-1',
        'ocd-division/country:us/state:vt/sldl:windsor-rutland-2',
        'ocd-division/country:us/state:vt/sldu:grand_isle',
        'ocd-division/country:us/state:ma/sldu:suffolk_and_norfolk',
        'ocd-division/country:us/state:ma/sldu:middlesex_suffolk_and_essex',
        'ocd-division/country:us/state:ma/sldu:middlesex_and_essex',
        'ocd-division/country:us/state:ma/sldu:hampshire_and_franklin',
        'ocd-division/country:us/state:ma/sldu:berkshire_hampshire_and_franklin',
        'ocd-division/country:us/state:ma/sldu:3rd_essex_and_middlesex',
        'ocd-division/country:us/state:wv/sldu:817',
        'ocd-division/country:us/state:nv/sldu:capital',
        'ocd-division/country:us/state:nv/sldu:central_nevada',
        'ocd-division/country:us/state:nv/sldu:clark_county_1',
        'ocd-division/country:us/state:nv/sldu:clark_county_2',
        'ocd-division/country:us/state:nv/sldu:clark_county_3',
        'ocd-division/country:us/state:nv/sldu:clark_county_4',
        'ocd-division/country:us/state:nv/sldu:clark_county_5',
        'ocd-division/country:us/state:nv/sldu:clark_county_6',
        'ocd-division/country:us/state:nv/sldu:clark_county_7',
        'ocd-division/country:us/state:nv/sldu:clark_county_8',
        'ocd-division/country:us/state:nv/sldu:clark_county_9',
        'ocd-division/country:us/state:nv/sldu:clark_county_10',
        'ocd-division/country:us/state:nv/sldu:clark_county_11',
        'ocd-division/country:us/state:nv/sldu:clark_county_12',
        'ocd-division/country:us/state:nv/sldu:rural_nevada',
        'ocd-division/country:us/state:nv/sldu:washoe_county_1',
        'ocd-division/country:us/state:nv/sldu:washoe_county_2',
        'ocd-division/country:us/state:nv/sldu:washoe_county_3',
        'ocd-division/country:us/state:nv/sldu:washoe_county_3'])
    URL = 'https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/master/identifiers/country-us.csv'
